✨ FE-281: Inherit Header and Footer from FE-102
arvin-viar/frontend-training pull request #8
Opened 2021-01-22 00:32 UTC by arvin-viar

2021-01-25 17:05 UTC, joshuacerbito requested changes

2021-01-25 17:05 UTC, joshuacerbito commented on fe-201/index.html
> +        <div class="main">
Please replace this `div` with `<main>`

2021-01-25 23:24 UTC, arvin-viar commented on fe-201/index.html
> +        <div class="main">
done, replacing `<div>` with `<main>`

2021-01-28 16:10 UTC, joshuacerbito approved these changes

2021-01-28 16:10 UTC, merged